## logistic regression : ovr

In [2]:
# 데이터 불러오기
import seaborn as sns # seaborn을 불러오고 SNS로 축약
import numpy as np
iris = sns.load_dataset('iris')  # iris라는 변수명으로 Iris data를 download
print(iris.head())
X = iris.drop('species', axis=1) # 'species'열을 drop하고 input X를 정의
y = iris['species']
print(np.unique(y))

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
['setosa' 'versicolor' 'virginica']


In [3]:
# y data를 범주형으로 변환
import numpy as np
from sklearn.preprocessing import LabelEncoder    # LabelEncoder() method를 불러옴
classle = LabelEncoder()
y = classle.fit_transform(iris['species'].values) # species 열의 문자열을 categorical 값으로 전환
print(np.unique(y))

[0 1 2]


In [4]:
# 전체 data를 training set과 test set으로 split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,
                                                    random_state=1, stratify=y)

In [5]:
# 표준화
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train) # train set만 적합
X_train_std = sc.transform(X_train) # 표준화로 변환 fit_transform 도 가능
X_test_std = sc.transform(X_test) # 표준화로 변환

In [6]:
# Logistic regression
from sklearn.linear_model import LogisticRegression
Logit = LogisticRegression(C=1e2, random_state=1, multi_class='ovr')  # C = 1/λ. 디폴트: L2, One-versus-Rest.  
l_1=Logit.fit(X_train_std, y_train)
y_train_pred = Logit.predict(X_train_std)
y_test_pred = Logit.predict(X_test_std)

In [8]:
# 계수 구하기
print(l_1.intercept_)
print(l_1.coef_)

[ -5.43052179  -1.03374577 -12.21594409]
[[-2.27467146  2.04221619 -4.01937844 -3.46372044]
 [-1.2777746  -0.93618002  3.53177076 -2.24098008]
 [-0.31117851 -2.10556199  9.51791722  8.48747802]]


## logistic regression : multinomial

In [10]:
Logit = LogisticRegression(C=1e2, random_state=1, multi_class='multinomial')  # C = 1/λ.
l_1=Logit.fit(X_train_std, y_train)
y_train_pred = Logit.predict(X_train_std)
y_test_pred = Logit.predict(X_test_std)

In [11]:
# 계수 구하기
print(l_1.intercept_)
print(l_1.coef_)

[ 0.60193841  6.1076602  -6.70959861]
[[-2.48710159  2.4086907  -5.41565289 -4.83270107]
 [ 1.46232628 -0.12532899 -2.35281482 -2.01137917]
 [ 1.02477531 -2.28336172  7.76846772  6.84408024]]
