In [2]:
from sklearn.datasets import load_digits
from sklearn.feature_selection import SelectKBest, chi2, f_classif, mutual_info_classif
x,y=load_digits(return_X_y=True)
x.shape

(1797, 64)

In [3]:
y.shape

(1797,)

In [4]:
x

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [5]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [6]:
import numpy as np
print(x[:2])
print(np.unique(y))

[[ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
  15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
   0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
   0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]
 [ 0.  0.  0. 12. 13.  5.  0.  0.  0.  0.  0. 11. 16.  9.  0.  0.  0.  0.
   3. 15. 16.  6.  0.  0.  0.  7. 15. 16. 16.  2.  0.  0.  0.  0.  1. 16.
  16.  3.  0.  0.  0.  0.  1. 16. 16.  6.  0.  0.  0.  0.  1. 16. 16.  6.
   0.  0.  0.  0.  0. 11. 16. 10.  0.  0.]]
[0 1 2 3 4 5 6 7 8 9]


In [15]:
import sklearn

1. chi2

In [13]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [7]:
sb=SelectKBest(score_func=chi2,k=20)
x_new=sb.fit_transform(x,y)
x_new.shape

(1797, 20)

In [23]:
x_new

array([[ 1.,  0., 15., ...,  6.,  0.,  0.],
       [ 5.,  0.,  9., ...,  0., 10.,  0.],
       [12.,  0., 14., ...,  0., 16.,  9.],
       ...,
       [ 1.,  0.,  2., ...,  2.,  6.,  0.],
       [ 0.,  0., 15., ...,  5., 12.,  0.],
       [ 1.,  0.,  1., ...,  8., 12.,  1.]])

In [17]:
sklearn.feature_selection.chi2(x, y)

(array([          nan,  811.90700411, 3501.28249552,  698.9252572 ,
         438.52969882, 3879.81925999, 3969.45823205, 1193.5608181 ,
          24.79521396, 2953.83108764, 2583.65198939,  388.24205944,
         824.69094853, 3676.48924765, 1983.5796061 ,  597.24198237,
           8.95886124, 1924.21690377, 2409.27140681, 3556.31594594,
        4871.94194551, 4782.19921618, 2155.17378998,  376.76583333,
           7.90090158, 2471.82418401, 4515.48149826, 2986.64314847,
        3724.09567634, 3208.64686641, 5138.07412439,   35.71270718,
                  nan, 5688.25079535, 5262.46646904, 3165.0605867 ,
        3231.63943369, 2532.99695611, 3288.81403655,           nan,
         142.85082873, 3863.85787901, 6416.0867248 , 5448.25154235,
        4079.73153383, 2134.02540236, 4486.34097862,  313.53898127,
          70.39927392,  449.72327313, 2801.97224468, 1527.54519627,
        1653.15892311, 3073.99803898, 5251.21748723,  683.88227339,
           9.15254237,  851.06791492, 3800.24731

In [9]:
sb.get_support()

array([False, False, False, False, False,  True,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False,  True,  True,  True, False, False, False, False,  True,
       False,  True, False,  True, False, False,  True,  True, False,
       False, False, False, False, False,  True,  True,  True,  True,
       False,  True, False, False, False, False, False, False, False,
        True, False, False, False,  True, False, False,  True,  True,
       False])

In [39]:
sb.scores_

array([          nan,  811.90700411, 3501.28249552,  698.9252572 ,
        438.52969882, 3879.81925999, 3969.45823205, 1193.5608181 ,
         24.79521396, 2953.83108764, 2583.65198939,  388.24205944,
        824.69094853, 3676.48924765, 1983.5796061 ,  597.24198237,
          8.95886124, 1924.21690377, 2409.27140681, 3556.31594594,
       4871.94194551, 4782.19921618, 2155.17378998,  376.76583333,
          7.90090158, 2471.82418401, 4515.48149826, 2986.64314847,
       3724.09567634, 3208.64686641, 5138.07412439,   35.71270718,
                 nan, 5688.25079535, 5262.46646904, 3165.0605867 ,
       3231.63943369, 2532.99695611, 3288.81403655,           nan,
        142.85082873, 3863.85787901, 6416.0867248 , 5448.25154235,
       4079.73153383, 2134.02540236, 4486.34097862,  313.53898127,
         70.39927392,  449.72327313, 2801.97224468, 1527.54519627,
       1653.15892311, 3073.99803898, 5251.21748723,  683.88227339,
          9.15254237,  851.06791492, 3800.2473108 ,  730.92975

In [38]:
sb.pvalues_

array([            nan, 5.81310493e-169, 0.00000000e+000, 1.17740541e-144,
       8.11314242e-089, 0.00000000e+000, 0.00000000e+000, 2.97727113e-251,
       3.20626273e-003, 0.00000000e+000, 0.00000000e+000, 4.41344943e-078,
       1.02825052e-171, 0.00000000e+000, 0.00000000e+000, 8.18335060e-123,
       4.41080315e-001, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 1.23435651e-075,
       5.44163062e-001, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 4.45801029e-005,
                   nan, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000,             nan,
       2.65875300e-026, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 3.49452723e-062,
       1.27145348e-011, 3.28604761e-091, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0

2. F

In [30]:
sb1=SelectKBest(score_func=f_classif,k=20)
x_new=sb1.fit_transform(x,y)
x_new.shape

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:114: UserWarning: Features [ 0 32 39] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx,
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:116: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


(1797, 20)

In [31]:
print(sb1.get_support())

[False False  True False False False False False False False  True False
 False  True False False False False False False  True  True False False
 False False  True False  True False  True False False  True  True False
  True False  True False False False  True  True  True False  True False
 False False False False False False  True False False False  True False
  True  True False False]


In [33]:
sb1.scores_

array([         nan,  39.77670877, 161.66962131,  68.01284271,
        37.085693  , 126.41541048,  74.26391138,  17.28204084,
         1.73328376,  93.87300085, 205.13348801,  38.86089592,
        51.62522088, 166.97247543,  37.41350206,  10.97417161,
         0.71100904,  55.32842977, 138.10227535, 138.68433936,
       202.43528942, 234.21960737,  50.24960622,  11.47100745,
         0.87782927, 103.80241354, 293.09983163, 146.07649117,
       236.7444881 , 127.5841692 , 189.18278073,   4.03517196,
                nan, 312.78489658, 254.37524393, 136.20370677,
       220.78357776, 110.63540569, 147.22496837,          nan,
         6.90281305, 123.36344683, 268.76998164, 222.53295915,
       159.07418303,  85.78384611, 169.33840921,  10.53627776,
         1.35922709,  12.19342228, 115.41402772,  83.87060144,
        88.50634019, 139.19382977, 162.49090456,  17.53002847,
         1.01703597,  35.49323239, 163.49692878,  68.70759521,
       200.35796882, 178.71033228, 106.03150882,  30.67

In [36]:
sb1.pvalues_

array([            nan, 4.99834376e-065, 8.12770776e-224, 7.82141288e-108,
       1.03883191e-060, 4.56052872e-184, 9.92420373e-117, 1.15850944e-027,
       7.66052413e-002, 2.05288354e-143, 7.83904161e-268, 1.45690786e-063,
       1.55742413e-083, 1.84517602e-229, 3.07811154e-061, 8.70497727e-017,
       6.99296954e-001, 3.74265221e-089, 1.07023842e-197, 2.30628015e-198,
       3.06673207e-265, 9.82716944e-295, 1.99271799e-081, 1.21078798e-017,
       5.44408914e-001, 2.86340363e-156, 0.00000000e+000, 9.88396955e-207,
       5.52772524e-297, 1.88118614e-185, 2.99386945e-252, 3.92803876e-005,
                   nan, 0.00000000e+000, 2.42398810e-312, 1.62783926e-195,
       1.54479017e-282, 7.04478594e-165, 5.13771578e-208,             nan,
       7.90550276e-010, 1.98515145e-180, 0.00000000e+000, 3.79380886e-284,
       5.03935070e-221, 1.26953521e-132, 5.94324696e-232, 4.94516665e-016,
       2.01446674e-001, 6.86214509e-019, 8.65547190e-171, 5.00690155e-130,
       2.74648230e-136, 6

3. 비선형

In [27]:
sb2=SelectKBest(score_func=f_classif,k=20)
x_new=sb2.fit_transform(x,y)
x_new.shape

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:114: UserWarning: Features [ 0 32 39] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx,
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:116: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw


(1797, 20)

In [29]:
sklearn.feature_selection.mutual_info_classif(x, y)

array([0.03876071, 0.13080304, 0.35818876, 0.19805004, 0.14808304,
       0.27014538, 0.19027399, 0.01954837, 0.        , 0.249466  ,
       0.31570968, 0.12740746, 0.19684073, 0.32786444, 0.11543189,
       0.05320948, 0.00501285, 0.18652016, 0.23541904, 0.26008413,
       0.34681717, 0.40785766, 0.23123594, 0.        , 0.0209109 ,
       0.24702469, 0.4105546 , 0.31659025, 0.3694494 , 0.31708752,
       0.40329281, 0.01056592, 0.02436367, 0.41525222, 0.42581568,
       0.29107293, 0.39564962, 0.239667  , 0.37497492, 0.00641388,
       0.01741318, 0.25445839, 0.432436  , 0.42088279, 0.2991033 ,
       0.18758035, 0.30985336, 0.01726463, 0.00914758, 0.05434345,
       0.27393833, 0.23727342, 0.20202931, 0.33698868, 0.36847802,
       0.09284238, 0.        , 0.13099908, 0.34857046, 0.20311145,
       0.30671429, 0.35824084, 0.29120876, 0.06747553])

In [28]:
print(sb2.get_support())

[False False  True False False False False False False False  True False
 False  True False False False False False False  True  True False False
 False False  True False  True False  True False False  True  True False
  True False  True False False False  True  True  True False  True False
 False False False False False False  True False False False  True False
  True  True False False]


In [32]:
sb2.scores_

array([         nan,  39.77670877, 161.66962131,  68.01284271,
        37.085693  , 126.41541048,  74.26391138,  17.28204084,
         1.73328376,  93.87300085, 205.13348801,  38.86089592,
        51.62522088, 166.97247543,  37.41350206,  10.97417161,
         0.71100904,  55.32842977, 138.10227535, 138.68433936,
       202.43528942, 234.21960737,  50.24960622,  11.47100745,
         0.87782927, 103.80241354, 293.09983163, 146.07649117,
       236.7444881 , 127.5841692 , 189.18278073,   4.03517196,
                nan, 312.78489658, 254.37524393, 136.20370677,
       220.78357776, 110.63540569, 147.22496837,          nan,
         6.90281305, 123.36344683, 268.76998164, 222.53295915,
       159.07418303,  85.78384611, 169.33840921,  10.53627776,
         1.35922709,  12.19342228, 115.41402772,  83.87060144,
        88.50634019, 139.19382977, 162.49090456,  17.53002847,
         1.01703597,  35.49323239, 163.49692878,  68.70759521,
       200.35796882, 178.71033228, 106.03150882,  30.67

In [34]:
sb2.pvalues_

array([            nan, 4.99834376e-065, 8.12770776e-224, 7.82141288e-108,
       1.03883191e-060, 4.56052872e-184, 9.92420373e-117, 1.15850944e-027,
       7.66052413e-002, 2.05288354e-143, 7.83904161e-268, 1.45690786e-063,
       1.55742413e-083, 1.84517602e-229, 3.07811154e-061, 8.70497727e-017,
       6.99296954e-001, 3.74265221e-089, 1.07023842e-197, 2.30628015e-198,
       3.06673207e-265, 9.82716944e-295, 1.99271799e-081, 1.21078798e-017,
       5.44408914e-001, 2.86340363e-156, 0.00000000e+000, 9.88396955e-207,
       5.52772524e-297, 1.88118614e-185, 2.99386945e-252, 3.92803876e-005,
                   nan, 0.00000000e+000, 2.42398810e-312, 1.62783926e-195,
       1.54479017e-282, 7.04478594e-165, 5.13771578e-208,             nan,
       7.90550276e-010, 1.98515145e-180, 0.00000000e+000, 3.79380886e-284,
       5.03935070e-221, 1.26953521e-132, 5.94324696e-232, 4.94516665e-016,
       2.01446674e-001, 6.86214509e-019, 8.65547190e-171, 5.00690155e-130,
       2.74648230e-136, 6