## LDA

In [1]:
import pandas as pd
import numpy as np

In [2]:
# 와인 데이터
# 데이터 불러오기. y값은 이미 범주형으로 되어있음.
# y class (1,2,3) 3개, 특성변수 x 13개
dat_wine=pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/'
                     'wine/wine.data',header=None)
print(dat_wine.head())
dat_wine.columns = ['class label', 'alchohol', 'malic acid', 'ash', 
                    'alcalinity of ash', 'magnesium', 'total phenols', 
                    'flavanoids', 'nonflavanoid phenols', 
                    'proanthocyanins', 'color intensity', 'hue', 
                    'OD208', 'proline']  # Column names
print('class label:', np.unique(dat_wine['class label']))  # Class 출력
dat_wine.head()

   0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735  
class label: [1 2 3]


class label  alchohol  malic acid   ash  alcalinity of ash  magnesium  \
0            1     14.23        1.71  2.43               15.6        127   
1            1     13.20        1.78  2.14               11.2        100   
2            1     13.16        2.36  2.67               18.6        101   
3            1     14.37        1.95  2.50               16.8        113   
4            1     13.24        2.59  2.87               21.0        118   

   total phenols  flavanoids  nonflavanoid phenols  proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   color intensity   hue  OD208  proline  
0             5.64  1.04   3.92     1065  
1             4.38  1.05   3.40     1050  
2             5.68  1.03   3.17     1185  
3             7.80  0.86   3.45     1480  
4             4.32  1.04   2.93      735

In [16]:
import scipy.stats as stats
test_stat, p_val = stats.shapiro(dat_wine.iloc[:,8])
print(test_stat)
print(p_val)

0.9625223875045776
0.00010552661115070805


In [21]:
print(dat_wine.shape)

(178, 14)


In [9]:
# 전체 data를 training set과 test set으로 split
from sklearn.model_selection import train_test_split
X, y = dat_wine.iloc[:,1:].values, dat_wine.iloc[:,0].values
X_train, X_test, y_train,y_test = \
    train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

In [10]:
# LDA 적합
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
cld=LinearDiscriminantAnalysis(store_covariance=True)
cld.fit(X_train, y_train) # LDA 적합
y_train_pred=cld.predict(X_train)
y_test_pred=cld.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_train, y_train_pred)) # train data에 대한 accuracy
print(accuracy_score(y_test, y_test_pred)) # test data에 대한 accuracy

1.0
0.9814814814814815


In [12]:
# 클래스별 평균
print(cld.means_)

[[1.36785366e+01 2.02317073e+00 2.45439024e+00 1.71365854e+01
  1.05341463e+02 2.86219512e+00 3.02731707e+00 2.89268293e-01
  1.95634146e+00 5.52000000e+00 1.06878049e+00 3.15609756e+00
  1.11382927e+03]
 [1.22118000e+01 2.02160000e+00 2.27140000e+00 2.06780000e+01
  9.34000000e+01 2.21060000e+00 2.04080000e+00 3.84000000e-01
  1.58700000e+00 3.04620000e+00 1.04052000e+00 2.77820000e+00
  4.94980000e+02]
 [1.31745455e+01 3.56666667e+00 2.42181818e+00 2.13181818e+01
  1.00212121e+02 1.68151515e+00 7.77878788e-01 4.48787879e-01
  1.17727273e+00 7.49424242e+00 6.86363636e-01 1.68090909e+00
  6.49090909e+02]]


In [13]:
# 특성변수의 평균
print(cld.xbar_)

[1.29529839e+01 2.43330645e+00 2.37193548e+00 1.96774194e+01
 9.91612903e+01 2.28524194e+00 2.03088710e+00 3.69919355e-01
 1.60008065e+00 5.04790323e+00 9.55612903e-01 2.61112903e+00
 7.40612903e+02]


In [14]:
# 각 x 마다 covariance 같기 때문에 13X13 한개 나옴
print(cld.covariance_)

[[ 2.41615068e-01  3.84592439e-02 -5.24867188e-03 -2.30283993e-03
  -7.86881482e-02  1.11713745e-02  1.33361710e-02 -4.67113583e-04
   1.07053192e-02  1.77454884e-01  4.91173257e-04 -1.62968428e-02
   8.54595097e+00]
 [ 3.84592439e-02  8.32381396e-01  2.83227199e-02  4.00338741e-01
  -5.87202072e-01 -9.42715080e-03 -9.52135930e-03  7.35759507e-03
   4.69856098e-02 -1.45330075e-01 -4.62261537e-02  5.60318655e-02
  -2.84926307e+01]
 [-5.24867188e-03  2.83227199e-02  6.80395376e-02  4.91619869e-01
   5.99821043e-01  2.86110643e-02  5.76375339e-02  7.22680996e-03
   4.46800139e-03  5.20767053e-02  3.63662334e-03  2.06618862e-02
  -5.77687326e-02]
 [-2.30283993e-03  4.00338741e-01  4.91619869e-01  8.43814527e+00
   4.38952042e+00  1.97406921e-01  4.41501428e-01  4.11469745e-02
   1.66482453e-01  5.67441496e-02  9.41799084e-04  3.51744582e-01
   4.43128671e+00]
 [-7.86881482e-02 -5.87202072e-01  5.99821043e-01  4.38952042e+00
   1.48134957e+02  8.43279534e-01  1.38061621e+00 -3.28155413e-01


In [15]:
print(cld.intercept_)

[-67.42856949  36.51807749  -1.65569344]


In [16]:
print(cld.coef_)

[[ 3.31363106e+00 -1.50074077e-01  3.52564251e+00 -8.89161617e-01
   1.52342343e-02 -2.17293267e+00  5.03235438e+00  3.12123703e+00
  -6.92880046e-01 -8.98897257e-01  1.13259908e+00  4.18153518e+00
   1.45033209e-02]
 [-2.46059543e+00 -5.42764250e-01 -5.84259880e+00  3.74068465e-01
  -7.58334217e-03 -6.65402628e-01  2.13832396e+00  5.34725357e+00
   4.54059921e-01 -5.81709854e-01  3.80466959e+00 -3.06608438e-01
  -7.64653043e-03]
 [-3.88760666e-01  1.00882575e+00  4.47207870e+00  5.37945547e-01
  -7.43746969e-03  3.70789002e+00 -9.49220387e+00 -1.19797999e+01
   1.72881390e-01  1.99819031e+00 -7.17181945e+00 -4.73068243e+00
  -6.43362530e-03]]


## QDA

In [17]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
cqd=QuadraticDiscriminantAnalysis(store_covariance=True)

cqd.fit(X_train, y_train) # QDA 적합
y_train_pred=cqd.predict(X_train)
y_test_pred=cqd.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_train, y_train_pred)) # train data에 대한 accuracy
print(accuracy_score(y_test, y_test_pred)) # test data에 대한 accuracy

1.0
0.9629629629629629


In [18]:
# 각 클래스의 평균
print(cqd.means_)

[[1.36785366e+01 2.02317073e+00 2.45439024e+00 1.71365854e+01
  1.05341463e+02 2.86219512e+00 3.02731707e+00 2.89268293e-01
  1.95634146e+00 5.52000000e+00 1.06878049e+00 3.15609756e+00
  1.11382927e+03]
 [1.22118000e+01 2.02160000e+00 2.27140000e+00 2.06780000e+01
  9.34000000e+01 2.21060000e+00 2.04080000e+00 3.84000000e-01
  1.58700000e+00 3.04620000e+00 1.04052000e+00 2.77820000e+00
  4.94980000e+02]
 [1.31745455e+01 3.56666667e+00 2.42181818e+00 2.13181818e+01
  1.00212121e+02 1.68151515e+00 7.77878788e-01 4.48787879e-01
  1.17727273e+00 7.49424242e+00 6.86363636e-01 1.68090909e+00
  6.49090909e+02]]


In [19]:
# 13개 특성 변수의 covariance 다르기 때문에 13X13이 13개 나옴
print(cqd.covariance_)

[array([[ 1.88392805e-01,  6.34225610e-03, -4.89091463e-03,
        -3.39720122e-01,  6.89012195e-01,  8.64857927e-02,
         1.01840976e-01,  3.54390244e-03,  7.13220122e-02,
         2.42672500e-01,  9.28067073e-03, -1.68353659e-04,
         3.81782439e+01],
       [ 6.34225610e-03,  4.38907195e-01,  4.16073171e-03,
        -1.00268902e-01,  6.11140244e-01, -1.74046341e-02,
        -3.93262805e-02, -1.19451220e-02,  6.80189024e-03,
        -1.98287500e-01, -2.79760366e-02,  5.71951829e-02,
        -5.63499451e+01],
       [-4.89091463e-03,  4.16073171e-03,  4.81202439e-02,
         2.03210366e-01,  7.39213415e-01,  3.69262195e-03,
        -5.40042683e-03,  6.14829268e-03, -1.97610366e-02,
        -3.14325000e-02,  5.37298780e-03, -2.10493902e-03,
        -4.20573171e+00],
       [-3.39720122e-01, -1.00268902e-01,  2.03210366e-01,
         5.99737805e+00,  3.34969512e+00, -2.46057317e-01,
        -3.70624390e-01,  3.18024390e-02, -2.83162805e-01,
        -6.45675000e-01,  2.89707317

## naive Bayesian

In [22]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train, y_train)
y_test_pred=gnb.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_train, y_train_pred)) # train data에 대한 accuracy
print(accuracy_score(y_test, y_test_pred))

1.0
0.9814814814814815


In [25]:
# 분류 결과
from sklearn.metrics import confusion_matrix 
mat=confusion_matrix(y_test, y_test_pred)
print(mat)

[[17  1  0]
 [ 0 21  0]
 [ 0  0 15]]
